apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: jarvis-ai
spec:
  selector:
    app: jarvis-backend
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
